name: Deploy Docs (MkDocs)

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch: {}

# Required for GitHub Pages (Actions) deployment flow
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Sync README and assets into docs
        run: |
          set -e
          mkdir -p docs
          # Always use README as the site homepage
          printf "# opcuaBaby\n\n" > docs/index.md
          cat README.md >> docs/index.md
          if [ -d assets ]; then
            rm -rf docs/assets
            cp -R assets docs/assets
          fi

      - name: Build site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
